# Site settings
title: CAES International Programs Office, UC Davis
email: lemcgarry@ucdavis.edu
description: > # this means to ignore newlines until "baseurl:"
  The CA&ES International Programs Office shares agricultural knowledge and information with the world. We conduct training and workshops, develop research/extension projects, advise on curricula development, sponsor global programs, offer educational opportunities, and guide capacity building.
subject: International Programs at UC Davis College of Agricultural and Environmental Sciences
classification: Web Design
author:
designer:
replyto:
themecolor: 22274d
repo: "https://github.com/ucdavis/ip"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ip.ucdavis.edu" # the base hostname & protocol for your site

permalink: pretty

paginate: 3

# Build settings
markdown: kramdown

#gems
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
