# Site settings
title: International Programs at UC Davis
email: seasercion@ucdavis.edu
description: > # this means to ignore newlines until "baseurl:"
  International programs of the College of Agricultural and Environmental Sciences facilitates the exchange of information and learning between UC Davis and the global community in the areas of agriculture and the environment.
subject: International Programs at UC Davis College of Agricultural and Environmental Sciences
classification: Non Profit, International Aid, Education
author: Steven Ascersion
designer: Cal Doval, cydoval@ucdavis.edu
replyto: 
themecolor: 22274d
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ip.ucdavis.edu" # the base hostname & protocol for your site

permalink: pretty

paginate: 3

# Build settings
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-sitemap
