# Site settings
title: International Programs Office at UC Davis
email: seacersion@ucdavis.edu
description: > # this means to ignore newlines until "baseurl:"
  International Programs brings agricultural knowledge and information to the world. We do training and workshops, research/extension projects, curricula development, sponsor global programs, offer educational opportunities, and capacity building.
subject: International Programs at UC Davis College of Agricultural and Environmental Sciences
classification: Web Design
author:
designer:
replyto:
themecolor: 22274d
repo: "https://github.com/ucdavis/ip"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ip.ucdavis.edu" # the base hostname & protocol for your site

permalink: pretty

paginate: 3

# Build settings
markdown: kramdown

#gems
gems:
  - jekyll-sitemap
  - jekyll-paginate
